# Generated by Django 4.0.5 on 2022-06-27 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_record_id_alter_tracklist_id'),
        ('main_app', '0003_record_image_two'),
    ]

    operations = [
    ]
