# Generated by Django 3.1.3 on 2022-06-27 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_record_image_two'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_name', models.CharField(max_length=100)),
                ('artist_age', models.IntegerField(verbose_name=100)),
                ('artist_location', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='record',
            name='artists',
            field=models.ManyToManyField(to='main_app.Artist'),
        ),
    ]
