# Generated by Django 3.1.3 on 2022-06-27 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_record_user'),
        ('main_app', '0004_auto_20220627_1303'),
    ]

    operations = [
    ]
