# Generated by Django 4.0.5 on 2022-06-27 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20220627_1303'),
        ('main_app', '0005_record_user'),
    ]

    operations = [
    ]
