# Generated by Django 4.0.5 on 2022-06-28 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_merge_0004_auto_20220627_1303_0005_record_user'),
        ('main_app', '0007_auto_20220627_1849'),
    ]

    operations = [
    ]
