# Generated by Django 3.1.3 on 2022-06-28 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_auto_20220628_0928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='records',
        ),
        migrations.AddField(
            model_name='record',
            name='artists',
            field=models.ManyToManyField(to='main_app.Artist'),
        ),
    ]

