# Generated by Django 4.0.5 on 2022-06-28 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_auto_20220628_1127'),
        ('main_app', '0011_crate_user'),
    ]

    operations = [
    ]
