# Generated by Django 4.0.5 on 2022-06-29 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_merge_0009_auto_20220628_1127_0011_crate_user'),
        ('main_app', '0012_merge_20220628_1146'),
    ]

    operations = [
    ]
