# Generated by Django 3.1.3 on 2022-06-28 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_merge_20220628_1146'),
        ('main_app', '0012_merge_0009_auto_20220628_1127_0011_crate_user'),
    ]

    operations = [
    ]
