# Generated by Django 4.0.5 on 2022-06-29 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_merge_20220628_1648'),
        ('main_app', '0013_merge_20220629_0755'),
    ]

    operations = [
    ]
