# Generated by Django 3.1.3 on 2022-06-29 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_auto_20220629_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='artist_age',
            field=models.IntegerField(blank=True, verbose_name='Artist Age'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='artist_location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='artist',
            name='artist_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
