# Generated by Django 3.1.3 on 2022-06-29 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_auto_20220629_1017'),
        ('main_app', '0014_merge_20220629_0806'),
    ]

    operations = [
    ]
