# Generated by Django 3.1.3 on 2022-06-29 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_merge_20220629_1137'),
        ('main_app', '0016_merge_20220629_1138'),
    ]

    operations = [
    ]
